{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Update sklearn to prevent version mismatches\n",
    "!pip install sklearn --upgrade"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "# install joblib. This will be used to save your model. \n",
    "# Restart your kernel after installing \n",
    "!pip install joblib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Read the CSV and Perform Basic Data Cleaning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>koi_disposition</th>\n",
       "      <th>koi_fpflag_nt</th>\n",
       "      <th>koi_fpflag_ss</th>\n",
       "      <th>koi_fpflag_co</th>\n",
       "      <th>koi_fpflag_ec</th>\n",
       "      <th>koi_period</th>\n",
       "      <th>koi_period_err1</th>\n",
       "      <th>koi_period_err2</th>\n",
       "      <th>koi_time0bk</th>\n",
       "      <th>koi_time0bk_err1</th>\n",
       "      <th>...</th>\n",
       "      <th>koi_steff_err2</th>\n",
       "      <th>koi_slogg</th>\n",
       "      <th>koi_slogg_err1</th>\n",
       "      <th>koi_slogg_err2</th>\n",
       "      <th>koi_srad</th>\n",
       "      <th>koi_srad_err1</th>\n",
       "      <th>koi_srad_err2</th>\n",
       "      <th>ra</th>\n",
       "      <th>dec</th>\n",
       "      <th>koi_kepmag</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>CONFIRMED</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>54.418383</td>\n",
       "      <td>2.479000e-04</td>\n",
       "      <td>-2.479000e-04</td>\n",
       "      <td>162.513840</td>\n",
       "      <td>0.003520</td>\n",
       "      <td>...</td>\n",
       "      <td>-81</td>\n",
       "      <td>4.467</td>\n",
       "      <td>0.064</td>\n",
       "      <td>-0.096</td>\n",
       "      <td>0.927</td>\n",
       "      <td>0.105</td>\n",
       "      <td>-0.061</td>\n",
       "      <td>291.93423</td>\n",
       "      <td>48.141651</td>\n",
       "      <td>15.347</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>FALSE POSITIVE</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>19.899140</td>\n",
       "      <td>1.490000e-05</td>\n",
       "      <td>-1.490000e-05</td>\n",
       "      <td>175.850252</td>\n",
       "      <td>0.000581</td>\n",
       "      <td>...</td>\n",
       "      <td>-176</td>\n",
       "      <td>4.544</td>\n",
       "      <td>0.044</td>\n",
       "      <td>-0.176</td>\n",
       "      <td>0.868</td>\n",
       "      <td>0.233</td>\n",
       "      <td>-0.078</td>\n",
       "      <td>297.00482</td>\n",
       "      <td>48.134129</td>\n",
       "      <td>15.436</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>FALSE POSITIVE</td>\n",
       "      <td>0</td>\n",
       "      <td>1</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>1.736952</td>\n",
       "      <td>2.630000e-07</td>\n",
       "      <td>-2.630000e-07</td>\n",
       "      <td>170.307565</td>\n",
       "      <td>0.000115</td>\n",
       "      <td>...</td>\n",
       "      <td>-174</td>\n",
       "      <td>4.564</td>\n",
       "      <td>0.053</td>\n",
       "      <td>-0.168</td>\n",
       "      <td>0.791</td>\n",
       "      <td>0.201</td>\n",
       "      <td>-0.067</td>\n",
       "      <td>285.53461</td>\n",
       "      <td>48.285210</td>\n",
       "      <td>15.597</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>CONFIRMED</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>2.525592</td>\n",
       "      <td>3.760000e-06</td>\n",
       "      <td>-3.760000e-06</td>\n",
       "      <td>171.595550</td>\n",
       "      <td>0.001130</td>\n",
       "      <td>...</td>\n",
       "      <td>-211</td>\n",
       "      <td>4.438</td>\n",
       "      <td>0.070</td>\n",
       "      <td>-0.210</td>\n",
       "      <td>1.046</td>\n",
       "      <td>0.334</td>\n",
       "      <td>-0.133</td>\n",
       "      <td>288.75488</td>\n",
       "      <td>48.226200</td>\n",
       "      <td>15.509</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>CONFIRMED</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>0</td>\n",
       "      <td>4.134435</td>\n",
       "      <td>1.050000e-05</td>\n",
       "      <td>-1.050000e-05</td>\n",
       "      <td>172.979370</td>\n",
       "      <td>0.001900</td>\n",
       "      <td>...</td>\n",
       "      <td>-232</td>\n",
       "      <td>4.486</td>\n",
       "      <td>0.054</td>\n",
       "      <td>-0.229</td>\n",
       "      <td>0.972</td>\n",
       "      <td>0.315</td>\n",
       "      <td>-0.105</td>\n",
       "      <td>296.28613</td>\n",
       "      <td>48.224670</td>\n",
       "      <td>15.714</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows Ã— 41 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "  koi_disposition  koi_fpflag_nt  koi_fpflag_ss  koi_fpflag_co  koi_fpflag_ec  \\\n",
       "0       CONFIRMED              0              0              0              0   \n",
       "1  FALSE POSITIVE              0              1              0              0   \n",
       "2  FALSE POSITIVE              0              1              0              0   \n",
       "3       CONFIRMED              0              0              0              0   \n",
       "4       CONFIRMED              0              0              0              0   \n",
       "\n",
       "   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  \\\n",
       "0   54.418383     2.479000e-04    -2.479000e-04   162.513840   \n",
       "1   19.899140     1.490000e-05    -1.490000e-05   175.850252   \n",
       "2    1.736952     2.630000e-07    -2.630000e-07   170.307565   \n",
       "3    2.525592     3.760000e-06    -3.760000e-06   171.595550   \n",
       "4    4.134435     1.050000e-05    -1.050000e-05   172.979370   \n",
       "\n",
       "   koi_time0bk_err1  ...  koi_steff_err2  koi_slogg  koi_slogg_err1  \\\n",
       "0          0.003520  ...             -81      4.467           0.064   \n",
       "1          0.000581  ...            -176      4.544           0.044   \n",
       "2          0.000115  ...            -174      4.564           0.053   \n",
       "3          0.001130  ...            -211      4.438           0.070   \n",
       "4          0.001900  ...            -232      4.486           0.054   \n",
       "\n",
       "   koi_slogg_err2  koi_srad  koi_srad_err1  koi_srad_err2         ra  \\\n",
       "0          -0.096     0.927          0.105         -0.061  291.93423   \n",
       "1          -0.176     0.868          0.233         -0.078  297.00482   \n",
       "2          -0.168     0.791          0.201         -0.067  285.53461   \n",
       "3          -0.210     1.046          0.334         -0.133  288.75488   \n",
       "4          -0.229     0.972          0.315         -0.105  296.28613   \n",
       "\n",
       "         dec  koi_kepmag  \n",
       "0  48.141651      15.347  \n",
       "1  48.134129      15.436  \n",
       "2  48.285210      15.597  \n",
       "3  48.226200      15.509  \n",
       "4  48.224670      15.714  \n",
       "\n",
       "[5 rows x 41 columns]"
      ]
     },
     "execution_count": 2,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df = pd.read_csv(\"exoplanet_data.csv\")\n",
    "# Drop the null columns where all values are null\n",
    "df = df.dropna(axis='columns', how='all')\n",
    "# Drop the null rows\n",
    "df = df.dropna()\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Select your features (columns)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>koi_period</th>\n",
       "      <th>koi_period_err1</th>\n",
       "      <th>koi_period_err2</th>\n",
       "      <th>koi_time0bk</th>\n",
       "      <th>koi_slogg</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>54.418383</td>\n",
       "      <td>2.479000e-04</td>\n",
       "      <td>-2.479000e-04</td>\n",
       "      <td>162.513840</td>\n",
       "      <td>4.467</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>19.899140</td>\n",
       "      <td>1.490000e-05</td>\n",
       "      <td>-1.490000e-05</td>\n",
       "      <td>175.850252</td>\n",
       "      <td>4.544</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>1.736952</td>\n",
       "      <td>2.630000e-07</td>\n",
       "      <td>-2.630000e-07</td>\n",
       "      <td>170.307565</td>\n",
       "      <td>4.564</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2.525592</td>\n",
       "      <td>3.760000e-06</td>\n",
       "      <td>-3.760000e-06</td>\n",
       "      <td>171.595550</td>\n",
       "      <td>4.438</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>4.134435</td>\n",
       "      <td>1.050000e-05</td>\n",
       "      <td>-1.050000e-05</td>\n",
       "      <td>172.979370</td>\n",
       "      <td>4.486</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   koi_period  koi_period_err1  koi_period_err2  koi_time0bk  koi_slogg\n",
       "0   54.418383     2.479000e-04    -2.479000e-04   162.513840      4.467\n",
       "1   19.899140     1.490000e-05    -1.490000e-05   175.850252      4.544\n",
       "2    1.736952     2.630000e-07    -2.630000e-07   170.307565      4.564\n",
       "3    2.525592     3.760000e-06    -3.760000e-06   171.595550      4.438\n",
       "4    4.134435     1.050000e-05    -1.050000e-05   172.979370      4.486"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Set features. This will also be used as your x values.\n",
    "selected_features = df[['koi_period', 'koi_period_err1', 'koi_period_err2', 'koi_time0bk', 'koi_slogg']]\n",
    "X = selected_features\n",
    "X.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Create a Train Test Split\n",
    "\n",
    "Use `koi_disposition` for the y values"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "\n",
    "y = df[\"koi_disposition\"]\n",
    "y = pd.get_dummies(y)\n",
    "# y.head()\n",
    "\n",
    "\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>koi_period</th>\n",
       "      <th>koi_period_err1</th>\n",
       "      <th>koi_period_err2</th>\n",
       "      <th>koi_time0bk</th>\n",
       "      <th>koi_slogg</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>6122</th>\n",
       "      <td>6.768901</td>\n",
       "      <td>7.380000e-05</td>\n",
       "      <td>-7.380000e-05</td>\n",
       "      <td>133.077240</td>\n",
       "      <td>4.327</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6370</th>\n",
       "      <td>0.733726</td>\n",
       "      <td>6.060000e-06</td>\n",
       "      <td>-6.060000e-06</td>\n",
       "      <td>132.020050</td>\n",
       "      <td>4.578</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2879</th>\n",
       "      <td>7.652707</td>\n",
       "      <td>6.540000e-05</td>\n",
       "      <td>-6.540000e-05</td>\n",
       "      <td>134.460380</td>\n",
       "      <td>4.481</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>107</th>\n",
       "      <td>7.953547</td>\n",
       "      <td>1.910000e-05</td>\n",
       "      <td>-1.910000e-05</td>\n",
       "      <td>174.662240</td>\n",
       "      <td>4.536</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>4.959319</td>\n",
       "      <td>5.150000e-07</td>\n",
       "      <td>-5.150000e-07</td>\n",
       "      <td>172.258529</td>\n",
       "      <td>4.359</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "      koi_period  koi_period_err1  koi_period_err2  koi_time0bk  koi_slogg\n",
       "6122    6.768901     7.380000e-05    -7.380000e-05   133.077240      4.327\n",
       "6370    0.733726     6.060000e-06    -6.060000e-06   132.020050      4.578\n",
       "2879    7.652707     6.540000e-05    -6.540000e-05   134.460380      4.481\n",
       "107     7.953547     1.910000e-05    -1.910000e-05   174.662240      4.536\n",
       "29      4.959319     5.150000e-07    -5.150000e-07   172.258529      4.359"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X_train.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Pre-processing\n",
    "\n",
    "Scale the data using the MinMaxScaler and perform some feature selection"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Scale data\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "X_scaler = StandardScaler().fit(X_train)\n",
    "y_scaler = StandardScaler().fit(y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [],
   "source": [
    "X_train_scaled = X_scaler.transform(X_train)\n",
    "X_test_scaled = X_scaler.transform(X_test)\n",
    "y_train_scaled = y_scaler.transform(y_train)\n",
    "y_test_scaled = y_scaler.transform(y_test)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "LinearRegression()"
      ]
     },
     "execution_count": 13,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "from sklearn.linear_model import LinearRegression\n",
    "model = LinearRegression()\n",
    "model.fit(X_train_scaled, y_train_scaled)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Train the Model\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Training Data Score: -0.5708106209944682\n",
      "Testing Data Score: -0.5590364804516611\n"
     ]
    }
   ],
   "source": [
    "print(f\"Training Data Score: {model.score(X_train_scaled, y_train)}\")\n",
    "print(f\"Testing Data Score: {model.score(X_test_scaled, y_test)}\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Hyperparameter Tuning\n",
    "\n",
    "Use `GridSearchCV` to tune the model's parameters"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "SVC(kernel='linear')"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Create the SVC Model\n",
    "from sklearn.svm import SVC \n",
    "model2 = SVC(kernel='linear')\n",
    "model2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create the GridSearchCV model\n",
    "from sklearn.model_selection import GridSearchCV\n",
    "\n",
    "param_grid = {'C': [1, 5, 10, 50],\n",
    "              'gamma': [0.0001, 0.0005, 0.001, 0.005]}\n",
    "grid2 = GridSearchCV(model2, param_grid, verbose=3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fitting 5 folds for each of 16 candidates, totalling 80 fits\n",
      "[CV] C=1, gamma=0.0001 ...............................................\n",
      "[CV] ..................... C=1, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.0001 ...............................................\n",
      "[CV] ..................... C=1, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.0001 ...............................................\n",
      "[CV] ..................... C=1, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.0001 ...............................................\n",
      "[CV] ..................... C=1, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.0001 ...............................................\n",
      "[CV] ..................... C=1, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.0005 ...............................................\n",
      "[CV] ..................... C=1, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.0005 ...............................................\n",
      "[CV] ..................... C=1, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.0005 ...............................................\n",
      "[CV] ..................... C=1, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.0005 ...............................................\n",
      "[CV] ..................... C=1, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.0005 ...............................................\n",
      "[CV] ..................... C=1, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.001 ................................................\n",
      "[CV] ...................... C=1, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.001 ................................................\n",
      "[CV] ...................... C=1, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.001 ................................................\n",
      "[CV] ...................... C=1, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.001 ................................................\n",
      "[CV] ...................... C=1, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.001 ................................................\n",
      "[CV] ...................... C=1, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.005 ................................................\n",
      "[CV] ...................... C=1, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.005 ................................................\n",
      "[CV] ...................... C=1, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.005 ................................................\n",
      "[CV] ...................... C=1, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.005 ................................................\n",
      "[CV] ...................... C=1, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=1, gamma=0.005 ................................................\n",
      "[CV] ...................... C=1, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.0001 ...............................................\n",
      "[CV] ..................... C=5, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.0001 ...............................................\n",
      "[CV] ..................... C=5, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.0001 ...............................................\n",
      "[CV] ..................... C=5, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.0001 ...............................................\n",
      "[CV] ..................... C=5, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.0001 ...............................................\n",
      "[CV] ..................... C=5, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.0005 ...............................................\n",
      "[CV] ..................... C=5, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.0005 ...............................................\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[CV] ..................... C=5, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.0005 ...............................................\n",
      "[CV] ..................... C=5, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.0005 ...............................................\n",
      "[CV] ..................... C=5, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.0005 ...............................................\n",
      "[CV] ..................... C=5, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.001 ................................................\n",
      "[CV] ...................... C=5, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.001 ................................................\n",
      "[CV] ...................... C=5, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.001 ................................................\n",
      "[CV] ...................... C=5, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.001 ................................................\n",
      "[CV] ...................... C=5, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.001 ................................................\n",
      "[CV] ...................... C=5, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.005 ................................................\n",
      "[CV] ...................... C=5, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.005 ................................................\n",
      "[CV] ...................... C=5, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.005 ................................................\n",
      "[CV] ...................... C=5, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.005 ................................................\n",
      "[CV] ...................... C=5, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=5, gamma=0.005 ................................................\n",
      "[CV] ...................... C=5, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.0001 ..............................................\n",
      "[CV] .................... C=10, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.0001 ..............................................\n",
      "[CV] .................... C=10, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.0001 ..............................................\n",
      "[CV] .................... C=10, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.0001 ..............................................\n",
      "[CV] .................... C=10, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.0001 ..............................................\n",
      "[CV] .................... C=10, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.0005 ..............................................\n",
      "[CV] .................... C=10, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.0005 ..............................................\n",
      "[CV] .................... C=10, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.0005 ..............................................\n",
      "[CV] .................... C=10, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.0005 ..............................................\n",
      "[CV] .................... C=10, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.0005 ..............................................\n",
      "[CV] .................... C=10, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.001 ...............................................\n",
      "[CV] ..................... C=10, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.001 ...............................................\n",
      "[CV] ..................... C=10, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.001 ...............................................\n",
      "[CV] ..................... C=10, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.001 ...............................................\n",
      "[CV] ..................... C=10, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.001 ...............................................\n",
      "[CV] ..................... C=10, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.005 ...............................................\n",
      "[CV] ..................... C=10, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.005 ...............................................\n",
      "[CV] ..................... C=10, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.005 ...............................................\n",
      "[CV] ..................... C=10, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.005 ...............................................\n",
      "[CV] ..................... C=10, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=10, gamma=0.005 ...............................................\n",
      "[CV] ..................... C=10, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.0001 ..............................................\n",
      "[CV] .................... C=50, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.0001 ..............................................\n",
      "[CV] .................... C=50, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.0001 ..............................................\n",
      "[CV] .................... C=50, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.0001 ..............................................\n",
      "[CV] .................... C=50, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.0001 ..............................................\n",
      "[CV] .................... C=50, gamma=0.0001, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.0005 ..............................................\n",
      "[CV] .................... C=50, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.0005 ..............................................\n",
      "[CV] .................... C=50, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.0005 ..............................................\n",
      "[CV] .................... C=50, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.0005 ..............................................\n",
      "[CV] .................... C=50, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.0005 ..............................................\n",
      "[CV] .................... C=50, gamma=0.0005, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.001 ...............................................\n",
      "[CV] ..................... C=50, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.001 ...............................................\n",
      "[CV] ..................... C=50, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.001 ...............................................\n",
      "[CV] ..................... C=50, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.001 ...............................................\n",
      "[CV] ..................... C=50, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.001 ...............................................\n",
      "[CV] ..................... C=50, gamma=0.001, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.005 ...............................................\n",
      "[CV] ..................... C=50, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.005 ...............................................\n",
      "[CV] ..................... C=50, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.005 ...............................................\n",
      "[CV] ..................... C=50, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.005 ...............................................\n",
      "[CV] ..................... C=50, gamma=0.005, score=nan, total=   0.0s\n",
      "[CV] C=50, gamma=0.005 ...............................................\n",
      "[CV] ..................... C=50, gamma=0.005, score=nan, total=   0.0s\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4194, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:552: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 531, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\", line 162, in fit\n",
      "    accept_large_sparse=False)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\", line 432, in _validate_data\n",
      "    X, y = check_X_y(X, y, **check_params)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 808, in check_X_y\n",
      "    y = column_or_1d(y, warn=True)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 73, in inner_f\n",
      "    return f(**kwargs)\n",
      "  File \"C:\\Users\\woodi\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\", line 848, in column_or_1d\n",
      "    \"got an array of shape {} instead.\".format(shape))\n",
      "ValueError: y should be a 1d array, got an array of shape (4195, 3) instead.\n",
      "\n",
      "  FitFailedWarning)\n",
      "[Parallel(n_jobs=1)]: Done  80 out of  80 | elapsed:    0.4s finished\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "y should be a 1d array, got an array of shape (5243, 3) instead.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-25-a334f82abc96>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[1;31m# Train the model with GridSearch\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 2\u001b[1;33m \u001b[0mgrid2\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX_train\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my_train\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m~\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\u001b[0m in \u001b[0;36minner_f\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     71\u001b[0m                           FutureWarning)\n\u001b[0;32m     72\u001b[0m         \u001b[0mkwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m{\u001b[0m\u001b[0mk\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0marg\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0mk\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0marg\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mzip\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msig\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mparameters\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 73\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     74\u001b[0m     \u001b[1;32mreturn\u001b[0m \u001b[0minner_f\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     75\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\model_selection\\_search.py\u001b[0m in \u001b[0;36mfit\u001b[1;34m(self, X, y, groups, **fit_params)\u001b[0m\n\u001b[0;32m    763\u001b[0m             \u001b[0mrefit_start_time\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtime\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    764\u001b[0m             \u001b[1;32mif\u001b[0m \u001b[0my\u001b[0m \u001b[1;32mis\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 765\u001b[1;33m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbest_estimator_\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    766\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    767\u001b[0m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mbest_estimator_\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mfit_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\svm\\_base.py\u001b[0m in \u001b[0;36mfit\u001b[1;34m(self, X, y, sample_weight)\u001b[0m\n\u001b[0;32m    160\u001b[0m             X, y = self._validate_data(X, y, dtype=np.float64,\n\u001b[0;32m    161\u001b[0m                                        \u001b[0morder\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'C'\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0maccept_sparse\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'csr'\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 162\u001b[1;33m                                        accept_large_sparse=False)\n\u001b[0m\u001b[0;32m    163\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    164\u001b[0m         \u001b[0my\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_validate_targets\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0my\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\base.py\u001b[0m in \u001b[0;36m_validate_data\u001b[1;34m(self, X, y, reset, validate_separately, **check_params)\u001b[0m\n\u001b[0;32m    430\u001b[0m                 \u001b[0my\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcheck_array\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mcheck_y_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    431\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 432\u001b[1;33m                 \u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcheck_X_y\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mcheck_params\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    433\u001b[0m             \u001b[0mout\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mX\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    434\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\u001b[0m in \u001b[0;36minner_f\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     71\u001b[0m                           FutureWarning)\n\u001b[0;32m     72\u001b[0m         \u001b[0mkwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m{\u001b[0m\u001b[0mk\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0marg\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0mk\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0marg\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mzip\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msig\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mparameters\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 73\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     74\u001b[0m     \u001b[1;32mreturn\u001b[0m \u001b[0minner_f\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     75\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\u001b[0m in \u001b[0;36mcheck_X_y\u001b[1;34m(X, y, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, multi_output, ensure_min_samples, ensure_min_features, y_numeric, estimator)\u001b[0m\n\u001b[0;32m    806\u001b[0m                         ensure_2d=False, dtype=None)\n\u001b[0;32m    807\u001b[0m     \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 808\u001b[1;33m         \u001b[0my\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mcolumn_or_1d\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0my\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mwarn\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    809\u001b[0m         \u001b[0m_assert_all_finite\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0my\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    810\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0my_numeric\u001b[0m \u001b[1;32mand\u001b[0m \u001b[0my\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdtype\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mkind\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;34m'O'\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\u001b[0m in \u001b[0;36minner_f\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     71\u001b[0m                           FutureWarning)\n\u001b[0;32m     72\u001b[0m         \u001b[0mkwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m{\u001b[0m\u001b[0mk\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0marg\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0mk\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0marg\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mzip\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msig\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mparameters\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 73\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     74\u001b[0m     \u001b[1;32mreturn\u001b[0m \u001b[0minner_f\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     75\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\anaconda3\\envs\\PythonData\\lib\\site-packages\\sklearn\\utils\\validation.py\u001b[0m in \u001b[0;36mcolumn_or_1d\u001b[1;34m(y, warn)\u001b[0m\n\u001b[0;32m    846\u001b[0m     raise ValueError(\n\u001b[0;32m    847\u001b[0m         \u001b[1;34m\"y should be a 1d array, \"\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 848\u001b[1;33m         \"got an array of shape {} instead.\".format(shape))\n\u001b[0m\u001b[0;32m    849\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    850\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mValueError\u001b[0m: y should be a 1d array, got an array of shape (5243, 3) instead."
     ]
    }
   ],
   "source": [
    "# Train the model with GridSearch\n",
    "grid2.fit(X_train, y_train)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "{'C': 1, 'gamma': 0.0001}\n"
     ]
    }
   ],
   "source": [
    "print(grid2.best_params_)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "nan\n"
     ]
    }
   ],
   "source": [
    "print(grid2.best_score_)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Save the Model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 31,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['burnettawood.csv']"
      ]
     },
     "execution_count": 31,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# save your model by updating \"your_name\" with your name\n",
    "# and \"your_model\" with your model variable\n",
    "# be sure to turn this in to BCS\n",
    "# if joblib fails to import, try running the command to install in terminal/git-bash\n",
    "import joblib\n",
    "filename = 'burnettawood.csv'\n",
    "joblib.dump(model2, filename)"
   ]
  }
 ],
 "metadata": {
  "kernel_info": {
   "name": "dev"
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.10"
  },
  "nteract": {
   "version": "0.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
